

#  Banco de dados
db.url=jdbc:sqlite:database/sisvale.db
db.foreign_keys=true

# Tolerância (em minutos) para considerar horários dentro da janela aceitável
regra.tolerancia.minutos=15

# ---------- UI ----------
ui.titulo=SisVale Interior
ui.tema=FlatLightLaf
ui.locale=pt_BR
ui.date.format=dd/MM/yyyy
ui.time.format=HH:mm

# ---------- Log ----------
log.dir=logs